#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffe5;
constexpr uint24_t FX_DATA_BYTES = 6660;

constexpr uint24_t boss1 = 0x000000;
constexpr uint16_t boss1Width  = 32;
constexpr uint16_t boss1Height = 22;
constexpr uint8_t  boss1Frames = 12;

constexpr uint24_t boss2 = 0x000484;
constexpr uint16_t boss2Width  = 24;
constexpr uint16_t boss2Height = 24;
constexpr uint8_t  boss2Frames = 3;

constexpr uint24_t bossCore = 0x000560;
constexpr uint16_t bossCoreWidth  = 8;
constexpr uint16_t bossCoreHeight = 8;

constexpr uint24_t carrierEnemy = 0x00056C;
constexpr uint16_t carrierEnemyWidth  = 32;
constexpr uint16_t carrierEnemyHeight = 32;
constexpr uint8_t  carrierEnemyFrames = 2;

constexpr uint24_t Cat = 0x000670;
constexpr uint16_t CatWidth  = 40;
constexpr uint16_t CatHeight = 64;

constexpr uint24_t enemieShips = 0x0007B4;
constexpr uint16_t enemieShipsWidth  = 8;
constexpr uint16_t enemieShipsHeight = 8;
constexpr uint8_t  enemieShipsFrames = 12;

constexpr uint24_t explosion = 0x000818;
constexpr uint16_t explosionWidth  = 8;
constexpr uint16_t explosionHeight = 8;
constexpr uint8_t  explosionFrames = 6;

constexpr uint24_t gateEnemy = 0x00087C;
constexpr uint16_t gateEnemyWidth  = 32;
constexpr uint16_t gateEnemyHeight = 24;
constexpr uint8_t  gateEnemyFrames = 3;

constexpr uint24_t headEnemy = 0x0009A0;
constexpr uint16_t headEnemyWidth  = 16;
constexpr uint16_t headEnemyHeight = 16;

constexpr uint24_t mainship = 0x0009C4;
constexpr uint16_t mainshipWidth  = 16;
constexpr uint16_t mainshipHeight = 16;
constexpr uint8_t  mainshipFrames = 2;

constexpr uint24_t midExplosion = 0x000A08;
constexpr uint16_t midExplosionWidth  = 16;
constexpr uint16_t midExplosionHeight = 16;
constexpr uint8_t  midExplosionFrames = 8;

constexpr uint24_t miniShips = 0x000B0C;
constexpr uint16_t miniShipsWidth  = 8;
constexpr uint16_t miniShipsHeight = 8;
constexpr uint8_t  miniShipsFrames = 16;

constexpr uint24_t powerups = 0x000B90;
constexpr uint16_t powerupsWidth  = 8;
constexpr uint16_t powerupsHeight = 8;
constexpr uint8_t  powerupsFrames = 4;

constexpr uint24_t snailware = 0x000BB4;
constexpr uint16_t snailwareWidth  = 64;
constexpr uint16_t snailwareHeight = 64;

constexpr uint24_t Title = 0x000DB8;
constexpr uint16_t TitleWidth  = 128;
constexpr uint16_t TitleHeight = 64;

constexpr uint24_t titleShip = 0x0011BC;
constexpr uint16_t titleShipWidth  = 96;
constexpr uint16_t titleShipHeight = 64;

constexpr uint24_t TitleText = 0x0017C0;
constexpr uint16_t TitleTextWidth  = 48;
constexpr uint16_t TitleTextHeight = 48;
constexpr uint8_t  TitleTextFrames = 2;

