#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff92;
constexpr uint24_t FX_DATA_BYTES = 27976;

constexpr uint24_t SNAILWARE_IMG = 0x000000;
constexpr uint24_t MAINSHIP_IMG = 0x000602;
constexpr uint24_t MINISHIPS_IMG = 0x000784;
constexpr uint24_t EXPLOSIONSMALL_IMG = 0x000906;
constexpr uint24_t CARRIERENEMY_IMG = 0x000A88;
constexpr uint24_t TITLESHIPB_IMG = 0x000D8A;
constexpr uint24_t BOSS1_IMG = 0x00168C;
constexpr uint24_t ENEMIESHIPS_IMG = 0x00240E;
constexpr uint24_t TITLESHIP2_IMG = 0x002530;
constexpr uint24_t GATEENEMY_IMG = 0x003732;
constexpr uint24_t EXPLOSION_IMG = 0x003A94;
constexpr uint24_t BOSSCORE_IMG = 0x003E56;
constexpr uint24_t CAT_IMG = 0x003E70;
constexpr uint24_t MIDEXPLOSION_IMG = 0x004232;
constexpr uint24_t TITLE_IMG = 0x004534;
constexpr uint24_t POWERUPS_IMG = 0x005136;
constexpr uint24_t TITLETEXT_IMG = 0x005198;
constexpr uint24_t HEADENEMY_IMG = 0x00585A;
constexpr uint24_t TITLESHIPT_IMG = 0x0058BC;
constexpr uint24_t BOSS2_IMG = 0x006ABE;
