#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff93;
constexpr uint24_t FX_DATA_BYTES = 27784;

constexpr uint24_t SNAILWARE_IMG = 0x000000;
constexpr uint24_t MAINSHIP_IMG = 0x000602;
constexpr uint24_t MINISHIPS_IMG = 0x0006C4;
constexpr uint24_t EXPLOSIONSMALL_IMG = 0x000846;
constexpr uint24_t CARRIERENEMY_IMG = 0x0009C8;
constexpr uint24_t TITLESHIPB_IMG = 0x000CCA;
constexpr uint24_t BOSS1_IMG = 0x0015CC;
constexpr uint24_t EXPLOSION_IMG = 0x00234E;
constexpr uint24_t ENEMIESHIPS_IMG = 0x002710;
constexpr uint24_t TITLESHIP2_IMG = 0x002832;
constexpr uint24_t GATEENEMY_IMG = 0x003A34;
constexpr uint24_t BOSSCORE_IMG = 0x003D96;
constexpr uint24_t CAT_IMG = 0x003DB0;
constexpr uint24_t MIDEXPLOSION_IMG = 0x004172;
constexpr uint24_t TITLE_IMG = 0x004474;
constexpr uint24_t POWERUPS_IMG = 0x005076;
constexpr uint24_t TITLETEXT_IMG = 0x0050D8;
constexpr uint24_t HEADENEMY_IMG = 0x00579A;
constexpr uint24_t TITLESHIPT_IMG = 0x0057FC;
constexpr uint24_t BOSS2_IMG = 0x0069FE;
